name: Rust code coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run rust test and code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Prepare cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo tools
        uses: taiki-e/install-action@cargo-tarpaulin

      - name: Run tests and code coverage
        run: cargo tarpaulin -o Lcov

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
